const ActionConstants = {
  Hooks: [
    "None",
    "Install",
    "Uninstall",
    "PlayerJoin",
    "PlayerLeave",
    "ElementAdd",
    "ElementUpdate",
    "ElementMove",
    "ElementRemove",
    "PropertyAdd",
    "PropertyUpdate",
    "PropertyRemove",
    "MapAdd",
    "MapUpdate",
    "MapRemove",
    "GameUpdate",
    "ChatMessage",
    "ChatCommand",
  ],

  StepTypes: {
    SendCommand: "Send Command",
    ExecuteAction: "Execute Action",
    GetData: "Get Data",
    GetDataCollection: "Get Data Collection",
    GetConnectedPlayers: "Get Connected Players",
    GetConnectedProperties: "Get Connected Properties",
    GetConnectedProperty: "Get Connected Property",
    SetVariable: "Set Variable",
    UserInputToVariable: "User Input To Variable",
    GetDetail: "Get Detail",
    GetElementDetail: "Get Element Detail",
    IfLabels: "If with Labels",
    If: "If",
    Calculate: "Calculate",
    While: "While",
    ForEach: "For Each",
    Exit: "Exit",
    SetElementDetail: "Set Element Detail",
    SetDetails: "Set Details",
    SetProperty: "Set Property",
    Sort: "Sort",
    Filter: "Filter",
    ShowPanel: "Show Panel",
    AddMenuButton: "Add Menu Button",
  },

  StepDefinitions: {
    SendCommand: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Command", label: "Command", toolTip: "Command to send.", type: "string" },
      { key: "Data", label: "Data", toolTip: "Data to send.", type: "string" },
      { key: "battlemapId", label: "Battlemap Id", toolTip: "Battlemap Id.", type: "string"},
      { key: "Action", label: "Action(This is not script action).", toolTip: "Additional parameter for command(This is not script action).", type: "string"}
    ],
    SetVariable: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Name", label: "Name", toolTip: "Name of map.", type: "string" },
      { key: "Value", label: "Value", toolTip: "Name of map.", type: "string" },
      { key: "Type", label: "Type", toolTip: "Type of map.", type: "string" }
    ],
    ExecuteAction: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Action", label: "Action", toolTip: "Action to execute.", type: "string" },
    ],
    GetConnectedProperties: [
      { key: "InputName", label: "Input Name", toolTip: "Name of input.", type: "string" },
      { key: "ParentId", label: "Parent ID", toolTip: ".", type: "string" },
      { key: "PropertyName", label: "Property Name", toolTip: ".", type: "string" },
      { key: "OutputName", label: "Output Name", toolTip: "Name of output.", type: "string" },
    ],
    GetConnectedProperty: [
      { key: "InputName", label: "Input Name", toolTip: "Name of input.", type: "string" },
      { key: "ParentId", label: "Parent ID", toolTip: ".", type: "string" },
      { key: "PropertyName", label: "Property Name", toolTip: ".", type: "string" },
      { key: "OutputName", label: "Output Name", toolTip: "Name of output.", type: "string" },
    ],
    GetData: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Type", label: "Data Type", toolTip: "Type of data to get.", type: "select", options: [{ value: "ElementModel", label: "Element" }, { value: "MapModel", label: "Map" }, { value: "PlayerModel", label: "Player" }, { value: "LayoutModel", label: "Layout" }, { value: "CardModel", label: "Card" }] },
      { key: "Id", label: "Data Id", toolTip: "Id of data to get.", type: "string" },
      { key: "Name", label: "Data Name", toolTip: "Name of data to get.", type: "string" },
      { key: "PropertyName", label: "Property Name", toolTip: "Name of property to get.", type: "string" },
      { key: "OutputName", label: "Output Name", toolTip: "Name of output.", type: "string" },
    ],
    GetDataCollection: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Type", label: "Data Type", toolTip: "Type of data to get.", type: "select", options: [{ value: "ElementModel", label: "Element" }, { value: "MapModel", label: "Map" }, { value: "PlayerModel", label: "Player" }, { value: "LayoutModel", label: "Layout" }, { value: "CardModel", label: "Card" }] },
      { key: "Id", label: "Data Id", toolTip: "Id of data to get.", type: "string" },
      { key: "Name", label: "Data Name", toolTip: "Name of data to get.", type: "string" },
      { key: "PropertyName", label: "Property Name", toolTip: "Name of property to get.", type: "string" },
      { key: "OutputName", label: "Output Name", toolTip: "Name of output.", type: "string" },
    ],
    GetConnectedPlayers: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "OutputName", label: "Output name", toolTip: "Label", type: "string" },
    ],
    GetDetail: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "InputName", label: "Input Name", toolTip: "Name of input.", type: "string" },
      { key: "DetailName", label: "Detail Name", toolTip: "Name of detail.", type: "string" },
      { key: "OutputName", label: "Output Name", toolTip: "Name of output.", type: "string" },
    ],
    GetElementDetail: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "InputName", label: "Input Name", toolTip: "Name of input.", type: "string" },
      { key: "DetailName", label: "Detail Name", toolTip: "Name of detail.", type: "string" },
      { key: "OutputName", label: "Output Name", toolTip: "Name of output.", type: "string" },
    ],
    UserInputToVariable: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Timeout", label: "Timeout", toolTip: "Name of input.", type: "string" },
      { key: "OutputName", label: "Output Name", toolTip: "Name of output.", type: "string" },
    ],
    IfLabels: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Condition", label: "Condition", toolTip: "Condition to check.", type: "string" },
      { key: "TrueLabel", label: "True Label", toolTip: "Label to go if true.", type: "string" },
      { key: "FalseLabel", label: "False Label", toolTip: "Label to go if false.", type: "string" },
    ],
    If: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Condition", label: "Condition", toolTip: "Condition to check.", type: "string" },
      { key: "ActionTrue", label: "Action if true", toolTip: "Action to execute if true.", type: "string" },
      { key: "ActionFalse", label: "Action if false", toolTip: "Action to execute if false.", type: "string" },
    ],
    Calculate: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Expression", label: "Expression", toolTip: "Operation to execute.", type: "string" },
      { key: "OutputName", label: "Output Name", toolTip: "Name of output.", type: "string" },
    ],
    While: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Condition", label: "Condition", toolTip: "Condition to check.", type: "string" },
      { key: "Action", label: "Action Name", toolTip: "Action", type: "string" },
    ],
    ForEach: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Collection", label: "Collection", toolTip: "Label", type: "string" },
      { key: "ItemName", label: "Output Item Name", toolTip: "ItemName", type: "string" },
      { key: "Action", label: "Action Name", toolTip: "Action", type: "string" },
    ],
    Exit: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
    ],
    SetElementDetail: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "InputName", label: "Input Name", toolTip: "Name of input.", type: "string" },
      { key: "Details", label: "Details", toolTip: "Name of detail.", type: "string" },
    ],
    SetDetails: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "InputName", label: "Input Name", toolTip: "Name of input.", type: "string" },
      { key: "Details", label: "Details", toolTip: "Name of detail.", type: "string" },
    ],
    AddMenuButton: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "Name", label: "Name", toolTip: "Name of button.", type: "string" },
      { key: "UiName", label: "Ui Name", toolTip: "Name of ui to be shown.", type: "string" },
      { key: "Icon", label: "Icon", toolTip: "Icon of button.", type: "string" },
      { key: "DataName", label: "Data", toolTip: "Data of button.", type: "string" },
      { key: "Action", label: "Action", toolTip: "Action of button.", type: "string" },
      { key: "Location", label: "Location", toolTip: "Location of button.", type: "string" },
    ],
    SetProperty: [
      { key: "Label", label: "Label", toolTip: "Label", type: "string" },
      { key: "PropertyName", label: "Name of property to be setted", toolTip: "Name of property.", type: "string" },
      { key: "ParentInputName", label: "Input name of parent", toolTip: "Name of input.", type: "string" },
      { key: "PropertyValue", label: "Value of property", toolTip: "Value of property.", type: "string" },
    ]
  },
}

export default ActionConstants;