name: Node.js CI

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_API_URL=${{ API_URL }} >> .env
          echo REACT_APP_WS_URL=${{ WS_URL }} >> .env
          echo REACT_APP_CARD_URL=${{ CARD_URL }} >> .env
          echo REACT_APP_IMAGE_URL=${{ IMAGE_URL }} >> .env
      - run: npm run build --if-present
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-build
      - run: ls dist
      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: public_html
        
